receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  debug:
    verbosity: detailed
  file/no_rotation:
    path: ./file-exporter/metrics.json

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [debug, file/no_rotation]
      processors: [batch]