name: CI
on:
  push:
    branches: [ main ]
  pull_request:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Install dependencies
        run: make deps

      - name: Build lspwatch
        run: make build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Install dependencies
        run: make deps

      - name: Build lspwatch with coverage
        run: make build-test

      - name: Run unit tests
        run: make unit-tests

      - name: Run integration tests
        run: make ci-integration-tests