name: Main CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Install dependencies
        run: make deps

      - name: Build lspwatch
        run: make build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Install dependencies
        run: make deps

      - name: Build lspwatch with coverage
        run: make build-test

      - name: Run unit tests
        run: make unit-tests

      - name: Run integration tests
        run: make ci-integration-tests

      - name: Combine coverage data into a profile
        run: go tool covdata textfmt -i=${{ github.workspace }}/coverage/unit,${{ github.workspace }}/coverage/integration -o=coverage.txt

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}