name: Main CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Install dependencies
        run: make deps

      - name: Build lspwatch
        run: make build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Install dependencies
        run: make deps

      - name: Build lspwatch with coverage
        run: make build-test

      - name: Run unit tests
        run: |
          echo "PWD: $PWD"
          echo "COVERAGE_DIR: $COVERAGE_DIR"
          make unit-tests

      - name: Run integration tests
        run: |
          echo "PWD: $PWD"
          echo "COVERAGE_DIR: $COVERAGE_DIR"
          make ci-integration-tests

      - name: Debug coverage
        run: |
          echo "Current directory: $PWD"
          echo "Looking for coverage files in: $COVERAGE_DIR"
          find . -name "*.coverdata" -o -name "covmeta*"

      - name: Debug coverage
        run: |
          echo "Unit test coverage files:"
          ls -la coverage/unit/
          echo "Integration test coverage files:"
          ls -la coverage/int/

      - name: Combine coverage data into a profile
        run: make combine-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}